default_config:
logger:
  default: error
  logs:
    custom_components.wienerlinien: debug

debugpy:

sensor:
  - platform: wienerlinien
    stops: '4429'
    firstnext: first
  - platform: wienerlinien
    stops: '4429'
    firstnext: next
  - platform: wienerlinien
    firstnext: first
    stops:
      - '4429'
      - '3230'
  - platform: wienerlinien
    stops: '149'
    firstnext: first
